import {C,H,Model,Parameters} from './model';
const NS='http://www.w3.org/2000/svg';
function el(tag:string,attrs:Record<string,string|number>,content=''){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));n.textContent=content;return n;}
function line(points:number[][]){return points.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(2)},${p[1].toFixed(2)}`).join(' ');}
export class LinkChart {
  cursor!:SVGLineElement; dot!:SVGCircleElement;svg:SVGSVGElement; bounds={left:58,right:976,top:24,bottom:206};low=0;high=60;model!:Model;
  constructor(host:HTMLElement,onScrub:(f:number)=>void){this.svg=el('svg',{viewBox:'0 0 1000 248',role:'img','aria-label':'Link margin along the rocket flight, beamformed and single patch'}) as SVGSVGElement;host.append(this.svg);let dragging=false;const scrub=(e:PointerEvent)=>{const r=this.svg.getBoundingClientRect();onScrub(Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*1000-58)/918)));};this.svg.addEventListener('pointerdown',e=>{dragging=true;this.svg.setPointerCapture(e.pointerId);scrub(e);});this.svg.addEventListener('pointermove',e=>{if(dragging)scrub(e);});this.svg.addEventListener('pointerup',()=>dragging=false);}
  draw(m:Model){this.model=m;this.svg.replaceChildren();const b=this.bounds;
    const raw=m.rows.flatMap(r=>[r[C.margin],r[C.marginSingle]]);this.low=Math.floor(Math.min(-5,...raw)/10)*10;this.high=Math.ceil(Math.max(10,...raw)/10)*10;
    const y=(v:number)=>b.bottom-(v-this.low)/(this.high-this.low)*(b.bottom-b.top);const x=(t:number)=>b.left+t/m.meta[H.duration]*(b.right-b.left);
    const defs=el('defs',{});const grad=el('linearGradient',{id:'chart-fill',x1:'0',y1:'0',x2:'0',y2:'1'});grad.append(el('stop',{offset:'0%','stop-color':'#65e4bd','stop-opacity':0.16}),el('stop',{offset:'100%','stop-color':'#65e4bd','stop-opacity':0}));defs.append(grad);this.svg.append(defs);
    this.svg.append(el('rect',{x:b.left,y:y(0),width:b.right-b.left,height:Math.max(0,b.bottom-y(0)),fill:'#fa987a','fill-opacity':0.045}));
    for(let v=this.low;v<=this.high;v+=10){this.svg.append(el('line',{x1:b.left,y1:y(v),x2:b.right,y2:y(v),stroke:v===0?'#815b52':'#1a2b35','stroke-dasharray':v===0?'5 5':'0'}),el('text',{x:b.left-14,y:y(v)+4,'text-anchor':'end',fill:'#708b9a','font-size':11},`${v}`));}
    this.svg.append(el('text',{x:12,y:15,fill:'#708b9a','font-size':10},'dB'));
    for(let i=0;i<=6;i++){const t=i*m.meta[H.duration]/6;this.svg.append(el('text',{x:x(t),y:233,'text-anchor':'middle',fill:'#708b9a','font-size':11},`${t.toFixed(0)} s`));}
    const beam=m.rows.map(r=>[x(r[C.time]),y(r[C.margin])]);const single=m.rows.map(r=>[x(r[C.time]),y(r[C.marginSingle])]);
    this.svg.append(el('path',{d:line(beam)+` L${b.right},${b.bottom} L${b.left},${b.bottom} Z`,fill:'url(#chart-fill)'}));
    this.svg.append(el('path',{d:line(single),fill:'none',stroke:'#718a99','stroke-width':1.8,'stroke-dasharray':'5 5'}),el('path',{d:line(beam),fill:'none',stroke:'#70e4bf','stroke-width':2.3}));
    for(const [t,label,color] of [[m.meta[H.burn],'BURNOUT','#ffb183'],[m.meta[H.apogeeT],'APOGEE','#91bacd']] as const){this.svg.append(el('line',{x1:x(t),y1:b.top,x2:x(t),y2:b.bottom,stroke:color,'stroke-opacity':0.25,'stroke-dasharray':'3 6'}),el('text',{x:x(t)+6,y:b.top-6,fill:color,'font-size':9,'letter-spacing':1},label));}
    const ref=x(m.meta[H.duration]*m.meta[H.aim]);this.svg.append(el('path',{d:`M${ref-4},${b.bottom+2} L${ref+4},${b.bottom+2} L${ref},${b.bottom+9} Z`,fill:'#ffb183'}));
    const mean=y(m.meta[H.mean]);this.svg.append(el('line',{x1:b.left,y1:mean,x2:b.right,y2:mean,stroke:'#70e4bf','stroke-opacity':0.3,'stroke-dasharray':'2 6'}));
    this.cursor=el('line',{x1:0,y1:b.top,x2:0,y2:b.bottom,stroke:'#d5efed','stroke-opacity':0.6}) as SVGLineElement;this.dot=el('circle',{cx:0,cy:0,r:4,fill:'#70e4bf',stroke:'#0c1922','stroke-width':2}) as SVGCircleElement;this.svg.append(this.cursor,this.dot);
  }
  select(f:number){if(!this.model)return;const x=58+f*918;this.cursor.setAttribute('x1',String(x));this.cursor.setAttribute('x2',String(x));const r=this.model.sample(f);this.dot.setAttribute('cx',String(x));this.dot.setAttribute('cy',String(206-(r[C.margin]-this.low)/(this.high-this.low)*182));}
}
export function polar(host:HTMLElement,model:Model,p:Parameters,steer:number[],isRx:boolean,cut=45){
  const svg=el('svg',{viewBox:'0 0 280 240',role:'img','aria-label':isRx?'Receiver gain elevation cut, absolute dBi':'Three dipole gain elevation cuts, absolute dBi'});const cx=140,cy=117,radius=86;const ceiling=isRx?15:10;const floor=-30;
  for(const v of [-30,-20,-10,0,ceiling]){const r=(v-floor)/(ceiling-floor)*radius;if(r>0)svg.append(el('circle',{cx,cy,r,fill:'none',stroke:'#223640','stroke-width':0.65}));svg.append(el('text',{x:cx+4,y:cy-r+11,fill:'#688493','font-size':8},`${v}`));}
  for(const a of [0,45,90,135,180,225,270,315]){const t=a*Math.PI/180;svg.append(el('line',{x1:cx,y1:cy,x2:cx+radius*Math.sin(t),y2:cy-radius*Math.cos(t),stroke:'#223640','stroke-width':0.65}));if(a%90===0)svg.append(el('text',{x:cx+(radius+16)*Math.sin(t),y:cy-(radius+16)*Math.cos(t)+4,'text-anchor':'middle',fill:'#688493','font-size':9},`${a}°`));}
  const paths=[false,true].map(beam=>{const pts:number[][]=[];for(let i=0;i<=720;i++){const t=i*Math.PI/360;const gain=isRx?model.rx(t,cut*Math.PI/180,p,steer,beam):model.tx(t,beam?Math.PI/2:0,p);const r=(Math.max(floor,gain)-floor)/(ceiling-floor)*radius;pts.push([cx+r*Math.sin(t),cy-r*Math.cos(t)]);}return line(pts);});
  svg.append(el('path',{d:paths[0],fill:isRx?'none':'#ffaa78','fill-opacity':0.045,stroke:isRx?'#7c96a4':'#ffaa78','stroke-width':1.7,'stroke-dasharray':isRx?'4 4':'0'}),el('path',{d:paths[1],fill:isRx?'#70e4bf':'none','fill-opacity':0.06,stroke:isRx?'#70e4bf':'#ffcdae','stroke-width':1.8,'stroke-dasharray':isRx?'0':'4 4'}));
  const reference:number[][]=[];for(let i=0;i<=720;i++){const t=i*Math.PI/360;const gain=isRx?model.rxFactor(t,cut*Math.PI/180,p,steer):model.single(t);const rr=(Math.max(floor,gain)-floor)/(ceiling-floor)*radius;reference.push([cx+rr*Math.sin(t),cy-rr*Math.cos(t)]);}svg.append(el('path',{d:line(reference),fill:'none',stroke:isRx?'#7eb4ff':'#738b96','stroke-width':1.2,'stroke-dasharray':'3 4'}));
  svg.append(el('text',{x:140,y:234,'text-anchor':'middle',fill:'#78909d','font-size':9},isRx?'0° = patch normal · dBi · −30 dBi floor':'0° = rocket axis · dBi · −30 dBi floor'));host.replaceChildren(svg);
}
export function azimuthPolar(host:HTMLElement,m:Model,p:Parameters){
  const svg=el('svg',{viewBox:'0 0 360 220',role:'img','aria-label':'Three dipole azimuth gain cut at 90 degrees to rocket axis'});const cx=180,cy=107,R=78,floor=-30,ceiling=10;
  for(const v of [-20,-10,0,10]){const r=(v-floor)/(ceiling-floor)*R;svg.append(el('circle',{cx,cy,r,fill:'none',stroke:'#28434f','stroke-width':.7}),el('text',{x:cx+4,y:cy-r+10,fill:'#7895a3','font-size':8},`${v} dBi`));}
  for(const a of [0,60,120,180,240,300]){const t=a*Math.PI/180;svg.append(el('line',{x1:cx,y1:cy,x2:cx+R*Math.sin(t),y2:cy-R*Math.cos(t),stroke:'#28434f','stroke-width':.7}),el('text',{x:cx+(R+13)*Math.sin(t),y:cy-(R+13)*Math.cos(t)+3,'text-anchor':'middle',fill:'#8ca9b5','font-size':9},`${a}°`));}
  const pts:number[][]=[];for(let i=0;i<=720;i++){const phi=i*Math.PI/360;const gain=m.tx(Math.PI/2,phi,p);const r=(Math.max(floor,gain)-floor)/(ceiling-floor)*R;pts.push([cx+r*Math.sin(phi),cy-r*Math.cos(phi)]);}
  svg.append(el('path',{d:line(pts),fill:'#ffaf7d','fill-opacity':.06,stroke:'#ffaf7d','stroke-width':2}),el('text',{x:180,y:215,'text-anchor':'middle',fill:'#87a6b4','font-size':10},'Azimuth around rocket axis · θ = 90°'));host.replaceChildren(svg);
}
export function angularMap(host:HTMLElement,m:Model,p:Parameters,steer:number[],rx:boolean){
  const canvas=document.createElement('canvas');const w=241,h=181;canvas.width=w;canvas.height=h;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',rx?'Receiver gain map showing all forward directions and grating lobes':'Three dipole gain map over elevation and azimuth, including interference nulls');
  const ctx=canvas.getContext('2d')!;const image=ctx.createImageData(w,h);const peak=rx?12.4897:m.meta[H.txPeak];const colors=[[9,17,29],[23,49,89],[64,77,137],[123,86,138],[202,115,117],[250,171,93],[248,231,162]];
  for(let y=0;y<h;y++){const phi=y/(h-1)*2*Math.PI;for(let x=0;x<w;x++){const theta=x/(w-1)*(rx?Math.PI/2:Math.PI);const gain=rx?m.rx(theta,phi,p,steer,true):m.tx(theta,phi,p);const value=Math.min(1,Math.max(0,(gain-peak+40)/40));const ci=value*(colors.length-1);const lower=Math.floor(ci),upper=Math.min(colors.length-1,lower+1),mix=ci-lower;const i=4*(y*w+x);for(let k=0;k<3;k++)image.data[i+k]=colors[lower][k]*(1-mix)+colors[upper][k]*mix;image.data[i+3]=255;}}
  ctx.putImageData(image,0,0);host.replaceChildren();const title=document.createElement('div');title.className='map-title';title.textContent=rx?'Full forward-hemisphere gain':'Full three-dipole angular gain';const axes=document.createElement('div');axes.className='map-axes';axes.innerHTML=`<span>φ 360°<br><br><br>0°</span><div class="map-image"></div>`;axes.querySelector('.map-image')!.append(canvas);const footer=document.createElement('div');footer.className='map-footer';footer.innerHTML=`<span>θ 0°</span><span>${rx?'90° patch plane':'180° aft axis'}</span>`;const scale=document.createElement('div');scale.className='map-scale';scale.innerHTML=`<span>${(peak-40).toFixed(1)} dBi</span><i></i><span>${peak.toFixed(1)} dBi</span>`;host.append(title,axes,footer,scale);
}
