import './style.css';
import {defaults,Parameters,Model,C,H} from './model';
import {Mission,PatternView,GeometryView} from './scene';
import {LinkChart,polar,angularMap,azimuthPolar} from './charts';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const number=(n:number,d=1)=>Number.isFinite(n)?n.toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const signed=(n:number,d=1)=>`${n>=0?'+':''}${number(n,d)}`;
const rate=(n:number)=>n>=1000?`${number(n/1000,2)} kb/s`:`${number(n,1)} b/s`;
const icon='<svg viewBox="0 0 32 32" fill="none"><path d="M16 3 23 23 16 19 9 23Z" fill="currentColor"/><path d="m13 23 3 7 3-7" stroke="currentColor"/><circle cx="16" cy="15" r="2" fill="#0c1821"/></svg>';
let p:Parameters={...defaults},position=.35,playing=false,lastTime=0;
try{if(location.hash.startsWith('#s=')){const s=JSON.parse(decodeURIComponent(location.hash.slice(3)));for(const key of Object.keys(defaults) as (keyof Parameters)[]){if(typeof s[key]===typeof defaults[key]&&(typeof s[key]==='boolean'||Number.isFinite(s[key])))Object.assign(p,{[key]:s[key]});}position=Math.min(1,Math.max(0,s.position??.35));}}catch{/* Start with defaults if a shared URL is malformed. */}
p.tracking=true;
const model=new Model();
function slider(key:keyof Parameters,label:string,min:number,max:number,step:number,hint:string,log=false){const value=p[key] as number;return `<div class="control"><div class="control-head"><label for="${key}">${label}</label><output id="${key}-value" for="${key}"></output></div><input id="${key}" data-param="${key}" type="range" min="${log?Math.log(min):min}" max="${log?Math.log(max):max}" step="${log?.005:step}" value="${log?Math.log(value):value}" ${log?'data-log="true"':''}><div class="control-foot"><span>${hint}</span></div></div>`;}
$('app').innerHTML=`
<header class="header"><a class="brand rakke-brand" href="https://igniteuit.no/rakke" target="_blank" rel="noopener" aria-label="Project Rakke at IgniteUiT"><span class="brand-logo"><img src="/igniterx/rakke-banner.png" alt="Rakke mission patch"></span><span>PROJECT RAKKE<small>COMMUNICATIONS · 868 MHz</small></span></a><nav aria-label="Sections"><a href="#mission">Mission</a><a href="#link">Link budget</a><a href="#patterns">Antennas</a><a href="#geometry">Geometry</a></nav><div class="header-end"><button id="share" class="button subtle">Share setup <span>↗</span></button><a class="github" href="https://github.com/jvierine/igniterx" target="_blank" rel="noopener" aria-label="Source on GitHub"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 .9a11.1 11.1 0 0 0-3.51 21.63c.55.1.76-.24.76-.54v-2.15c-3.09.67-3.75-1.31-3.75-1.31-.51-1.28-1.23-1.62-1.23-1.62-1.01-.69.08-.68.08-.68 1.12.08 1.71 1.15 1.71 1.15.99 1.7 2.6 1.21 3.23.93.1-.72.38-1.21.7-1.49-2.47-.28-5.06-1.23-5.06-5.49 0-1.21.43-2.2 1.15-2.98-.12-.28-.5-1.42.11-2.96 0 0 .94-.3 3.06 1.14a10.7 10.7 0 0 1 5.58 0c2.12-1.44 3.06-1.14 3.06-1.14.61 1.54.23 2.68.11 2.96.72.78 1.15 1.77 1.15 2.98 0 4.28-2.6 5.2-5.08 5.48.4.35.76 1.02.76 2.06v3.12c0 .3.2.65.77.54A11.1 11.1 0 0 0 12 .9Z"/></svg></a></div></header>
<main><section class="intro"><div><div class="eyebrow"><span class="dot"></span>IGNITEUIT / ANDØYA SPACE CENTER</div><h1>Rakke communications link budget</h1></div><div class="frequency"><span>868</span><div>MHz<small>λ = 34.54 cm</small></div></div></section>
<section class="metrics" aria-label="Flight link summary"><article><span class="metric-label">AVERAGE LINK MARGIN</span><div><strong id="mean">—</strong><span>dB</span><svg class="metric-spark" viewBox="0 0 90 32"><path d="m1 25 10-5 9 3 12-14 10 4 10-10 9 4 11-5 8 3" fill="none" stroke="currentColor" stroke-width="2"/></svg></div><small>Time-weighted across the full flight</small></article><article><span class="metric-label">WORST LINK MARGIN</span><div><strong id="worst">—</strong><span>dB</span><i id="worst-state" class="metric-pill">—</i></div><small id="worst-caption">Minimum of 601 flight samples</small></article><article><span class="metric-label">LINK AVAILABILITY</span><div><strong id="availability">—</strong><span>%</span></div><small>Flight time with margin ≥ 0 dB</small></article><article><span class="metric-label">TARGET APOGEE</span><div><strong>3.00</strong><span>km</span><i class="metric-pill neutral">CALIBRATED</i></div><small id="flight-duration">Constant mass flow · powered + ballistic</small></article></section>
<div class="layout"><aside class="sidebar"><div class="sidebar-title"><h2>Mission parameters</h2><button id="reset" class="text-button">Reset ↺</button></div><section class="control-section"><h3><span>01</span> Ground station</h3><div class="hardware">5 × CP patch <span>5.5 dBi / element</span><small>Cross array → KrakenSDR → LoRa DSP</small></div>${slider('rxSpacing','Element spacing',.5,2,.005,'Center → outer patch · 0.5–2.0 λ')}${slider('offset','Receiver stand-off',100,2000,10,'Behind pad · crossrange offset 150 m')}<label class="select-label" for="tracking">Beam steering</label><select id="tracking"><option value="true" selected>Track rocket electronically</option></select><p class="field-note">The plane stays fixed. Tracking adjusts the five digital phase weights.</p></section>
<section class="control-section"><h3><span>02</span> Rocket transmitter</h3><div class="hardware">3 × half-wave dipole <span>Equal phase / equal amplitude</span><small>120° apart around the nose · axial elements</small></div>${slider('power','Total transmit power',1,500,1,'Total radiated power shared by 3 elements')}${slider('txSpacing','Dipole spacing',.05,1,.005,'Nearest-neighbor chord · 0.05–1.0 λ')}${slider('roll','Antenna roll',0,120,1,'Array rotation about the rocket axis')}</section>
<section class="control-section"><h3><span>03</span> Flight & orientation</h3>${slider('zenith','Launch zenith angle',0,60,1,'0° vertical · downrange azimuth 330°')}
<label class="select-label" for="attitude">Rocket attitude</label><select id="attitude"><option value="false" ${!p.attitude?'selected':''}>Hold launch attitude</option><option value="true" ${p.attitude?'selected':''}>Align with velocity</option></select></section>
<section class="control-section"><h3><span>04</span> LoRa & noise</h3>${slider('rate','Required PHY bit rate',18.3,37500,1,'Auto-select SF6–12 · CR 4/5',true)}${slider('temperature','System noise temperature',100,10000,1,'Equivalent total system temperature',true)}${slider('loss','Feed / insertion loss',0,15,.1,'Tx + Rx loss outside antenna gains')}${slider('reserve','Demodulation reserve',0,15,.1,'Added to the ideal LoRa SNR threshold')}<div class="modem-card"><span>AUTO-SELECTED LORA MODE</span><strong id="modem">—</strong><small id="modem-rate">Selecting the most sensitive eligible mode…</small></div></section>
<div class="sidebar-bottom"><span class="dot"></span>Rust physics · WebAssembly · WebGL</div></aside>
<div class="workspace"><section id="mission" class="panel mission-panel"><div class="panel-heading"><div><span class="eyebrow">01 / FLIGHT GEOMETRY</span><h2>Flight & antenna beams</h2></div><div class="scene-tools"><button id="camera-home" class="icon-button" title="Reset camera" aria-label="Reset camera">⌂</button><button id="camera-side" class="icon-button" title="Side view" aria-label="Side view">▱</button><button id="fullscreen" class="icon-button" title="Fullscreen" aria-label="Fullscreen">⛶</button></div></div><div id="scene-shell"><div id="scene" class="scene"><div class="scene-gradient"></div><div class="scene-info"><span class="scene-tag"><i></i> ANDØYA · NORWAY</span><span>Local flight frame · schematic coast</span></div><div class="flight-readout"><span id="phase" class="phase">COASTING</span><strong id="altitude">—<small>m altitude</small></strong><div><span>Slant range</span><b id="range">—</b></div><div><span>Speed</span><b id="speed">—</b></div><div><span>Link margin</span><b id="current-margin">—</b></div></div><div class="scene-bottom"><span>DRAG TO ORBIT · SCROLL TO ZOOM</span><div class="beam-switches"><label><input id="show-array-beam" type="checkbox" checked> Array −3 dB beam</label><label><input id="show-single-beam" type="checkbox" checked> Single patch −3 dB</label></div></div></div><div class="timeline"><button id="play" class="play-button" aria-label="Play flight">▶</button><div class="timeline-track"><div class="timeline-labels"><span id="current-time">T + 00.0 s</span><span id="timeline-status">COASTING</span><span id="end-time">— s</span></div><input id="position" type="range" min="0" max="1" step=".001" value="${position}" aria-label="Rocket position along flight"><div class="timeline-markers"><span>IGNITION</span><span id="burn-marker">BURNOUT</span><span id="apogee-marker">APOGEE</span><span>TOUCHDOWN</span></div></div></div><div class="reference-controls"><div class="reference-slider">${slider('aim','Array reference point',0,1,.001,'Flight time · sets the plane normal')}</div><button id="optimize" class="button optimize">◎ Optimize worst-case margin</button></div></div><div class="scene-caption"><span><i class="legend-line orange"></i>Powered flight</span><span><i class="legend-line teal"></i>Coast / descent</span><span><i class="legend-line dashed orange"></i>Array reference</span><span><i class="legend-line muted"></i>Single patch beam</span><span id="beam-width" class="beam-width"></span><span id="tilt-caption">Array tilt —</span></div></section>
<section id="link" class="panel"><div class="panel-heading"><div><span class="eyebrow">02 / TELEMETRY PERFORMANCE</span><h2>Link margin over flight</h2></div><button id="csv" class="button subtle">Export CSV ↓</button></div><div class="chart-legend"><span><i class="legend-line teal"></i>Five-channel beamformer</span><span><i class="legend-line dashed muted"></i>Single patch · fixed broad beam</span><span><i class="legend-line dashed salmon"></i>0 dB threshold</span></div><div id="chart" class="link-chart"></div><div class="chart-foot"><span>Click or drag the plot to inspect the flight.</span><span id="link-mode">FIXED BEAM · FREE SPACE</span></div></section>
<section class="panel budget-panel"><div class="panel-heading"><div><span class="eyebrow">03 / FRIIS LINK BUDGET</span><h2>The link at <span id="budget-time">—</span></h2></div><span class="small-badge">868 MHz</span></div><div class="budget-grid"><div class="budget-equation"><span>Pᵣ = Pₜ + Gₜ + Gᵣ − Lfs − Lpol − Lfeed</span><div class="budget-row"><span>Total transmit power</span><b id="budget-power">—</b></div><div class="budget-row"><span>3-dipole gain toward Rx</span><b id="budget-tx">—</b></div><div class="budget-row"><span>5-channel effective receive gain</span><b id="budget-rx">—</b></div><div class="budget-row"><span>Free-space path loss</span><b id="budget-fs">—</b></div><div class="budget-row"><span>Linear → circular polarization</span><b>−3.01 dB</b></div><div class="budget-row"><span>Feed / insertion loss</span><b id="budget-loss">—</b></div><div class="budget-row total"><span>Effective received power</span><b id="budget-pr">—</b></div></div><div class="noise-budget"><div class="budget-row"><span>Thermal noise · kTₛᵧₛB</span><b id="budget-noise">—</b></div><div class="budget-row"><span>LoRa SNR threshold</span><b id="budget-snr">—</b></div><div class="budget-row"><span>Demodulation reserve</span><b id="budget-reserve">—</b></div><div class="budget-row"><span>Estimated sensitivity</span><b id="budget-sensitivity">—</b></div><div class="margin-result"><span>LINK MARGIN</span><strong id="budget-margin">—</strong><small id="budget-reception">—</small></div><div class="doppler"><span>Instantaneous Doppler</span><b id="doppler">—</b></div></div></div></section>
<section id="geometry" class="panel"><div class="panel-heading"><div><span class="eyebrow">04 / ANTENNA GEOMETRY</span><h2>Antenna locations & orientation</h2></div><button id="rx-closeup" class="button subtle">Ground array in flight view</button></div><div class="geometry-grid"><div><h3>Ground array · five CP patches</h3><div id="rx-geometry" class="geometry-webgl"></div><p id="rx-geometry-caption" class="pattern-caption"></p></div><div><h3>Rocket cone · three axial dipoles</h3><div id="tx-geometry" class="geometry-webgl"></div><p id="tx-geometry-caption" class="pattern-caption"></p></div></div></section>
<section id="patterns" class="patterns"><article class="panel pattern-panel"><div class="panel-heading"><div><span class="eyebrow">04 / GROUND ARRAY</span><h2>The receiving beam</h2></div><span class="small-badge green">5 × PATCH</span></div><div class="pattern-visual"><div id="rx-pattern" class="pattern-webgl"></div><div id="rx-polar" class="polar"></div></div><div class="pattern-stats"><div><span>PATCH PEAK</span><b>5.50 <small>dBi</small></b></div><div><span>IDEAL ARRAY PEAK</span><b>12.49 <small>dBi</small></b></div><div><span>COMBINING GAIN</span><b>6.99 <small>dB</small></b></div></div><div class="pattern-note"><span><i class="legend-line teal"></i>Total Rx gain</span><span><i class="legend-line dashed muted"></i>Single patch</span><span><i class="legend-line dashed blue"></i>Array factor only</span></div><label class="cut-control" for="rx-cut">Elevation cut φ<select id="rx-cut"><option value="0">0°</option><option value="45" selected>45°</option><option value="90">90°</option></select></label><div id="rx-map" class="angular-map"></div><p id="rx-pattern-caption" class="pattern-caption">Fixed beam about the patch normal.</p></article>
<article class="panel pattern-panel"><div class="panel-heading"><div><span class="eyebrow">05 / ROCKET ARRAY</span><h2>Combined three-dipole pattern</h2></div><span class="small-badge orange-text">3 × DIPOLE</span></div><div class="pattern-visual"><div id="tx-pattern" class="pattern-webgl"></div><div id="tx-polar" class="polar"></div></div><div class="pattern-stats"><div><span>ARRAY PEAK</span><b id="tx-peak">—</b></div><div><span>DIPOLE LENGTH</span><b>17.27 <small>cm</small></b></div><div><span>CHORD SPACING</span><b id="tx-chord">—</b></div></div><div class="pattern-note"><span><i class="legend-line orange"></i>3 dipoles · φ = 0°</span><span><i class="legend-line dashed peach"></i>φ = 90°</span><span><i class="legend-line dashed muted"></i>Single dipole</span></div><div id="tx-azimuth" class="azimuth-cut"></div><div id="tx-map" class="angular-map"></div><p class="pattern-caption">Equal-phase complex field sum · fixed total radiated power.</p></article></section>

<section class="panel slide-links"><div class="panel-heading"><h2>Slide decks</h2><a href="https://juha.no/space/" target="_blank" rel="noopener" class="text-button">Course index ↗</a></div><div class="slide-decks"><a href="https://juha.no/space/friis-voyager/" target="_blank" rel="noopener">Friis transmission equation ↗</a><a href="https://juha.no/space/telecom-modulations/" target="_blank" rel="noopener">Digital modulation ↗</a><a href="https://juha.no/space/planck-to-ktb/" target="_blank" rel="noopener">Planck law & radio noise ↗</a><a href="https://juha.no/space/link-budget/" target="_blank" rel="noopener">Link budget & bit error rate ↗</a></div></section>

<footer><span><a href="https://igniteuit.no/rakke" target="_blank" rel="noopener">Project Rakke · IgniteUiT ↗</a></span><span>Built with Rust, WebAssembly & WebGL <a href="https://github.com/jvierine/igniterx">View source ↗</a></span></footer></div></div></main><div id="toast" role="status" aria-live="polite"></div><div id="fatal" role="alert" hidden></div>`;
const formatParam=(key:keyof Parameters,n:number)=>{switch(key){case'rxSpacing':case'txSpacing':return `${number(n,2)} λ / ${number(n*299792458/868e6*100,1)} cm`;case'power':return `${number(n,0)} mW`;case'zenith':case'roll':return `${number(n,0)}°`;case'temperature':return `${number(n,0)} K`;case'rate':return rate(n);case'offset':return `${number(n,0)} m`;case'aim':return model.meta?`${number(n*model.meta[H.duration],1)} s / ${number(n*100,0)}%`:`${number(n*100,0)}%`;default:return `${number(n,1)} dB`;}};
function updateControlLabels(){for(const input of document.querySelectorAll<HTMLInputElement>('input[data-param]')){const key=input.dataset.param as keyof Parameters;const val=p[key] as number;input.value=String(input.dataset.log?Math.log(val):val);const fraction=(Number(input.value)-Number(input.min))/(Number(input.max)-Number(input.min));input.style.setProperty('--fill',`${Math.max(0,Math.min(100,fraction*100))}%`);$(`${key}-value`).textContent=formatParam(key,val);input.setAttribute('aria-valuetext',formatParam(key,val));}}
let mission:Mission,rxView:PatternView,txView:PatternView,rxGeometry:GeometryView,txGeometry:GeometryView,chart:LinkChart;
function put(id:string,text:string){$(id).textContent=text;}
function patternUpdate(){const steer=mission.steerLocal();rxView.build(model,p,steer,true);polar($('rx-polar'),model,p,steer,true,Number($<HTMLSelectElement>('rx-cut').value));angularMap($('rx-map'),model,p,steer,true);put('rx-pattern-caption',p.tracking?`Tracking at ${number(model.sample(position)[C.offAxis],1)}° off normal. The patch envelope stays fixed.`:'Fixed equal-phase beam about the patch normal.');}
function recalculate(){model.calculate(p);p.aim=model.meta[H.aim];updateControlLabels();const m=model.meta;
  put('mean',signed(m[H.mean]));put('worst',signed(m[H.worst]));$('worst').classList.toggle('negative',m[H.worst]<0);put('availability',number(m[H.availability],1));put('worst-state',m[H.worst]>=0?'CLOSED':'OUTAGE');$('worst-state').classList.toggle('bad',m[H.worst]<0);const worst=model.rows.reduce((a,b)=>a[C.margin]<b[C.margin]?a:b);put('worst-caption',`At T + ${number(worst[C.time],1)} s · ${number(worst[C.z],0)} m altitude`);put('flight-duration',`${number(m[H.duration],1)} s flight · ${number(m[H.apogeeT],1)} s to apogee`);
  put('modem',`SF${m[H.sf]} / ${number(m[H.bw]/1000,1)} kHz / 4:5`);put('modem-rate',`${rate(m[H.rate])} available · ${number(m[H.sensitivity],1)} dBm sensitivity`);put('end-time',`${number(m[H.duration],1)} s`);put('tilt-caption',`Plane tilt ${number(m[H.tilt],1)}° from horizontal`);put('link-mode',`${p.tracking?'TRACKING':'FIXED'} BEAM · FREE SPACE`);put('tx-peak',`${number(m[H.txPeak],2)} dBi`);put('tx-chord',`${number(m[H.txD]*100,1)} cm`);
  $('burn-marker').style.left=`${m[H.burn]/m[H.duration]*100}%`;$('apogee-marker').style.left=`${m[H.apogeeT]/m[H.duration]*100}%`;
  mission.build(model,p);chart.draw(model);txView.build(model,p,[0,0,1],false);polar($('tx-polar'),model,p,[0,0,1],false);azimuthPolar($('tx-azimuth'),model,p);angularMap($('tx-map'),model,p,[0,0,1],false);rxGeometry.build(model,p,true);txGeometry.build(model,p,false);put('rx-geometry-caption',`d = ${number(m[H.rxD]*100,1)} cm · center height 2 m · tilt ${number(m[H.tilt],1)}°. All five patches are above ground.`);put('tx-geometry-caption',`Dipole length 17.27 cm · chord ${number(m[H.txD]*100,1)} cm · 120° apart. Cone dimensions schematic; dipoles parallel to the rocket axis.`);patternUpdate();select(position);
}
let patternTime=0;
function select(f:number){position=Math.min(1,Math.max(0,f));const r=model.sample(position);const m=model.meta;const phase=r[C.burning]?'POWERED ASCENT':r[C.time]<m[H.apogeeT]?'BALLISTIC ASCENT':'BALLISTIC DESCENT';
  put('current-time',`T + ${number(r[C.time],1)} s`);put('phase',phase);put('timeline-status',phase);$('phase').classList.toggle('burning',!!r[C.burning]);$('altitude').innerHTML=`${number(r[C.z],0)}<small>m altitude</small>`;put('range',`${number(r[C.range]/1000,2)} km`);put('speed',`${number(Math.hypot(r[C.vx],r[C.vy],r[C.vz]),0)} m/s`);put('current-margin',`${signed(r[C.margin])} dB`);$('current-margin').classList.toggle('negative',r[C.margin]<0);
  const input=$<HTMLInputElement>('position');input.value=String(position);input.style.setProperty('--fill',`${position*100}%`);
  put('budget-time',`T + ${number(r[C.time],1)} s`);put('budget-power',`${signed(m[H.power])} dBm`);put('budget-tx',`${signed(r[C.tx])} dBi`);put('budget-rx',`${signed(r[C.rx])} dBi`);put('budget-fs',`−${number(r[C.fspl])} dB`);put('budget-loss',`−${number(p.loss)} dB`);put('budget-pr',`${number(r[C.pr])} dBm`);put('budget-noise',`${number(m[H.noise])} dBm`);put('budget-snr',`${number(m[H.snr])} dB`);put('budget-reserve',`${signed(p.reserve)} dB`);put('budget-sensitivity',`${number(m[H.sensitivity])} dBm`);put('budget-margin',`${signed(r[C.margin])} dB`);$('budget-margin').classList.toggle('negative',r[C.margin]<0);put('budget-reception',r[C.margin]>=0?'Above the estimated decode threshold':'Below the estimated decode threshold');put('doppler',`${signed(r[C.doppler],0)} Hz`);
  mission.select(position,!playing);put('beam-width',`Array beamwidth ${number(mission.beamWidth,1)}° · single patch 90°`);txGeometry.orient(model,p,position);chart.select(position);if(p.tracking&&(!playing||performance.now()-patternTime>150)){patternTime=performance.now();patternUpdate();}
}
function toast(message:string){put('toast',message);$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500);}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function stop(){playing=false;put('play','▶');$('play').setAttribute('aria-label','Play flight');}
async function boot(){await model.init();mission=new Mission($('scene'),f=>{stop();select(f);});rxView=new PatternView($('rx-pattern'));txView=new PatternView($('tx-pattern'));rxGeometry=new GeometryView($('rx-geometry'));txGeometry=new GeometryView($('tx-geometry'));chart=new LinkChart($('chart'),f=>{stop();select(f);});recalculate();
  let pending=0;for(const input of document.querySelectorAll<HTMLInputElement>('input[data-param]')){input.addEventListener('input',()=>{const key=input.dataset.param as keyof Parameters;const value=Number(input.value);Object.assign(p,{[key]:input.dataset.log?Math.exp(value):value});updateControlLabels();cancelAnimationFrame(pending);pending=requestAnimationFrame(recalculate);});}
  for(const key of ['tracking','attitude'] as const){$(key).addEventListener('change',()=>{p[key]=$<HTMLSelectElement>(key).value==='true';recalculate();});}
  $('position').addEventListener('input',()=>{stop();select(Number($<HTMLInputElement>('position').value));});
  $('play').addEventListener('click',()=>{playing=!playing;if(playing){if(position>=.999)select(0);lastTime=performance.now();put('play','Ⅱ');$('play').setAttribute('aria-label','Pause flight');}else stop();});
  const tick=(now:number)=>{requestAnimationFrame(tick);if(!playing||document.hidden){lastTime=now;return;}const delta=Math.min(.1,(now-lastTime)/1000);lastTime=now;select(position+delta/18);if(position>=1){stop();select(1);}};requestAnimationFrame(tick);
  $('reset').addEventListener('click',()=>{stop();p={...defaults};position=.35;$<HTMLSelectElement>('tracking').value='true';$<HTMLSelectElement>('attitude').value='false';recalculate();toast('Default Rakke setup restored');});
  $('optimize').addEventListener('click',()=>{stop();p.aim=-1;recalculate();toast(`Array aligned at T + ${number(p.aim*model.meta[H.duration],1)} s for the best sampled worst-case margin`);});
  $('rx-closeup').addEventListener('click',()=>{mission.closeup();$('mission').scrollIntoView({behavior:'smooth'});});$('rx-cut').addEventListener('change',patternUpdate);$('camera-home').addEventListener('click',()=>mission.reset());$('camera-side').addEventListener('click',()=>mission.side());$('show-array-beam').addEventListener('change',()=>{mission.arrayBeam.visible=$<HTMLInputElement>('show-array-beam').checked;});$('show-single-beam').addEventListener('change',()=>{mission.singleBeam.visible=$<HTMLInputElement>('show-single-beam').checked;});
  $('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('scene-shell').requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser');}});
  $('share').addEventListener('click',async()=>{const url=new URL(location.href);url.hash=`s=${encodeURIComponent(JSON.stringify({...p,position}))}`;history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);toast('Setup link copied to clipboard');}catch{toast('Setup saved in the address bar — copy the URL to share');}});
  $('csv').addEventListener('click',()=>{const headers=['time_s','downrange_m','crossrange_m','altitude_m','vx_m_s','vy_m_s','vz_m_s','mass_kg','burning','slant_range_m','tx_gain_dbi','single_patch_gain_dbi','effective_rx_gain_dbi','fspl_db','single_patch_power_dbm','beamformed_power_dbm','noise_dbm','sensitivity_dbm','single_patch_margin_db','beamformed_margin_db','doppler_hz','rx_off_axis_deg'];const meta=`# IgniteRX 868 MHz; settings=${JSON.stringify(p)}\n# Flight: wet=12 kg; dry=8 kg; burn=4 s; ve=${model.meta[H.ve]} m/s; mean=${model.meta[H.mean]} dB; worst=${model.meta[H.worst]} dB; availability=${model.meta[H.availability]}%; SF=${model.meta[H.sf]}; BW=${model.meta[H.bw]} Hz; CR=4/5\n`;download('rakke-link-budget.csv',meta+headers.join(',')+'\n'+model.rows.map(r=>Array.from(r).map(n=>n.toPrecision(10)).join(',')).join('\n'),'text/csv');toast('Flight link budget exported');});
  (window as unknown as {igniterx:unknown}).igniterx={model,get parameters(){return {...p};},get position(){return position;}};
}
updateControlLabels();boot().catch(error=>{console.error(error);$('fatal').hidden=false;$('fatal').textContent=`The simulation could not start: ${error.message}. Reload the page or use a browser with WebAssembly and WebGL 2 support.`;});
